export { Hero } from './Hero'
export { DecisionSpace } from './DecisionSpace'
export { LifeMapCompass } from './LifeMapCompass'
export { ProposalCards } from './ProposalCards'
export type { Proposal } from './ProposalCards'
export { Acceptance } from './Acceptance'
export { ScrollIndicator } from './ScrollIndicator'
export { LenisProvider } from './LenisProvider'
export { ParallaxSection, ParallaxText, ParallaxImage, StaggerChildren, staggerItem } from './ParallaxMotion'
